# Cloudflare Pages Configuration
name = "jaydus-ai-platform"
compatibility_date = "2024-01-01"

# Pages build output directory (excludes internal docs)
pages_build_output_dir = "public"

# Environment variables for production
[env.production]
vars = { }

# Custom domain will be added via dashboard